---

containers:

  - name   : postgres
    build  : .ci/postgres/setup.sh
    export :
      - POSTGRES_IP

  - name   : postgREST
    build  : .ci/postgREST/setup.sh
    export :
      - POSTGREST_IP

  - name  : jobs
    build : .ci/jobs/setup.sh

steps:

  - name      : Test Suite
    container : jobs
    script    : .ci/jobs/tests.sh

  - name      : Deploy Package
    container : jobs
    script    : .ci/jobs/package.sh
